name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Specify the Java version you are using

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.java') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests and check results
      run: |
        mvn test  # This runs the tests
        if grep -q "Tests run:" target/surefire-reports/*.txt; then
          echo "Tests passed."
        else
          echo "Tests failed. Please check the test logs for more details."
          exit 1  # Fail the job if tests fail
        fi
